DROP TABLE trainer CASCADE CONSTRAINTS;
DROP TABLE trainee CASCADE CONSTRAINTS;
DROP TABLE studio CASCADE CONSTRAINTS;
DROP TABLE muskel CASCADE CONSTRAINTS;
DROP TABLE geraet CASCADE CONSTRAINTS;
DROP TABLE uebung CASCADE CONSTRAINTS;
DROP TABLE training CASCADE CONSTRAINTS;
DROP TABLE konditioniert CASCADE CONSTRAINTS;
DROP TABLE trainingspartner CASCADE CONSTRAINTS;

DROP SEQUENCE m_id_seq;
DROP VIEW geraeteanzahl_oe;
DROP VIEW counter;

